apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: nginx
    targetRevision: 9.7.6
    repoURL: https://charts.bitnami.com/bitnami
  destination:
    server: https://kubernetes.default.svc
    namespace: chapter10
  syncPolicy:
    automated:
      prune: true
      selfHeal: true