{{- if .Values.redis.master.persistence.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "guestbook.fullname" . }}-{{ .Values.redis.fullnameOverride }}-restore-{{ .Release.Revision }}
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: backup
          image: redis:alpine3.15
          command: ["/bin/sh", "-c"]
          args:
            - |-
              cp /backup/dump.rdb /data/dump.rdb
              redis-cli -h {{ .Values.redis.fullnameOverride }}-master debug restart || true
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: backup
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-{{ .Values.redis.fullnameOverride }}-master-0
        - name: backup
          persistentVolumeClaim:
            claimName: {{ include "guestbook.fullname" . }}-{{ .Values.redis.fullnameOverride }}-backup-{{ .Release.Revision }}
{{- end }}
