apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "guestbook.fullname" . }}-rollout
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
