---
book:
  chapter6:
    props:
      chapterNumber: 6
      chapterName: Understanding Helm Templates
  keywords:
    - kubernetes
    - developer
    - cloud
service:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
